export const NAV_LINKS = [
  {
    key: 1,
    value: "Store",
  },
  {
    key: 2,
    value: "Orders",
  },
  {
    key: 3,
    value: "Analytics",
  },
];

export const ORDER = {
  id: "12345BC",
  supplier: "ABC Organics",
  shipping_date: "08-11-2023",
  currency: "$",
  total: 1000.2,
  category: ["F"],
  department: "200-100-444",
  status: 1,
  status_desc: "Awaiting Approval",
  list: [
    {
      id: "P1",
      name: "TEST 1",
      brand: "B1",
      price: 100,
      quantity: 1,
      total: 100,
      status: "",
    },
    {
      id: "P2",
      name: "TEST 2",
      brand: "B2",
      price: 200,
      quantity: 1,
      total: 200,
      status: "",
    },
    {
      id: "P3",
      name: "TEST 3",
      brand: "B3",
      price: 200,
      quantity: 1,
      total: 200,
      status: "",
    },
    {
      id: "P4",
      name: "TEST 4",
      brand: "B4",
      price: 200,
      quantity: 1,
      total: 200,
      status: "",
    },
    {
      id: "P5",
      name: "TEST 5",
      brand: "B5",
      price: 200,
      quantity: 1,
      total: 200,
      status: "",
    },
    {
      id: "P6",
      name: "TEST 6",
      brand: "B6",
      price: 200,
      quantity: 1,
      total: 200,
      status: "",
    },
  ],
};
